# Adapted from Code Institute e-commerce lesson in Full Stack Frameworks module,
# Also incorporating the information from 
# https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
# to support use of Python 3.7

language: python

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - DEVELOPMENT=true
        - HOSTNAME='0.0.0.0'
        - IP='0.0.0.0'
        - PORT='5000'
        - SECRET_KEY="whatever" 

install: "pip3 install -r requirements.txt"

script:
  python3 manage.py test || python manage.py test