# Adapted from Code Institute e-commerce lesson in Full Stack Frameworks module,
# Also incorporating the information from 
# https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
# to support use of Python 3.7

language: python

matrix:
  include:
    - python: 3.8
      sudo: true
      env:
        - DEVELOPMENT=true
        - HOSTNAME='0.0.0.0'
        - IP='0.0.0.0'
        - PORT='5000'
        - SECRET_KEY="whatever" 

install: "pip3 install -r requirements.txt"